CREATE DATABASE OOP;
USE OOP;
CREATE TABLE oop_info(stu_id INT NOT NULL, PRIMARY KEY(stu_id), stu_name CHAR,grade INT);
INSERT INTO oop_info(stu_id, stu_name,grade) VALUES (2018011243, "alice",100);
INSERT INTO oop_info(stu_id, stu_name,grade) VALUES (2018011043, "bob",90);
INSERT INTO oop_info(stu_id, stu_name,grade) VALUES (2018010243, "darwen",92);
INSERT INTO oop_info(stu_id, stu_name,grade) VALUES (2018001344, "akira",93);
INSERT INTO oop_info(stu_id, stu_name,grade) VALUES (2018001394, "sophie",99);
INSERT INTO oop_info(stu_id, stu_name,grade) VALUES (2018011445, "sai",98);
SELECT MAX(grade) from oop_info;
SELECT MAX(grade) from oop_info GROUP BY stu_name;
SELECT MIN(grade) from oop_info;
SELECT MIN(grade) from oop_info GROUP BY stu_name;
SELECT ASCII(stu_name) from oop_info;
SELECT CHAR_LENGTH(stu_name) from oop_info;
